config/routes.rb
Rails.application.routes.draw do

  get 'climbs/grouped_ratings', to: 'climbs#ratings'

  resources :reviews
  
  resources :climbs do
    resources :reviews, only: [:new, :show, :index]
  end 
  
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end

  root to: 'application#welcome'
  get 'home', to: 'application#home'

  get '/search', to: 'climbs#search'

  get '/locations', to: 'application#welcome'

  resources :locations

  get '*path', to: 'application#welcome'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/climb.rb
class Climb < ApplicationRecord

    has_many :reviews
    has_many :users, through: :reviews
  
    belongs_to :location
  
    accepts_nested_attributes_for :location
  
    validates :name, presence: true
    validates :grade, presence: true

    scope :grouped_ratings, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')}

    scope :search, -> (query) { where("name LIKE ?", "%" + query + "%") }


    def self.alphabetical_order
        order(:name)
    end 
    

    def location_attributes=(location_attributes)
        location_name = location_attributes["name"]
        unless location_name.blank?
             location = Location.find_or_create_by(name: location_name)
             self.location = location
        end
    end

end

app/models/location.rb
class Location < ApplicationRecord

    has_many :climbs
    
    validates :name, presence: true

    def self.alphabetical_order
        order(:name)
    end

end
 

app/models/review.rb
class Review < ApplicationRecord

    belongs_to :climb
    belongs_to :user

    validates :stars, presence: true
    validates :title, presence: true
    validates :content, presence: true
    validates :user_id, presence: true 
    
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[github]

  has_many :reviews
  has_many :climbs, through: :reviews

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :username, presence: true 

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

    def home 
      require_login 
      if current_user && !(current_user.username.present?)
        current_user.username = current_user.email
      end
    end 

    def welcome
      redirect_to home_path if user_signed_in?
    end

    def require_login
        unless user_signed_in?
          flash[:danger] = "You must be logged in to access this section!"
          redirect_to root_path
        end
    end
    
end

app/controllers/climbs_controller.rb
class ClimbsController < ApplicationController

    before_action :require_login
    before_action :find_climb, only: [:show]
   

    def index
        @climbs = Climb.all.alphabetical_order
    end

    def new
        @climb = Climb.new
        @climb.build_location
        locations
    end
 
    def create
        @climb = Climb.new(climb_params)
        if @climb.save
            redirect_to climbs_path
        else
            @climb.build_location
            locations
            render :new
        end
    end

    def show
        unless !(@climb == nil)
            redirect_to climbs_path
        end 
    end

    def ratings
        @climbs = Climb.grouped_ratings
    end

    def search
        @climbs = Climb.search(params[:query])
        render :index
    end

    private

    def climb_params
        params.require(:climb).permit(:name, :grade, :description, :location_id, location_attributes: [:name])
    end

    def find_climb
        @climb = Climb.find_by(id: params[:id])
    end

    def locations
        @locations = Location.all.alphabetical_order
    end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

    before_action :require_login
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
    
    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :require_login
    before_action :find_review, only: [:show, :edit, :update, :destroy]
    before_action :created_by_current_user, only: [:edit, :update, :destroy]

    def index
        if find_climb
            @reviews = @climb.reviews.all  
        else
            climbs
            @reviews = Review.all
        end   

    end

    def new
        if find_climb
            @review = @climb.reviews.build
        else
            climbs
            @review = Review.new
        end    
    end

    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
            flash[:message] = "Thanks for the spray!"
            redirect_to review_path(@review)
        else
            climbs
            render :new
        end
    end

    def show
        unless !(@review == nil)
            redirect_to reviews_path
        end  
    end 

    def edit
        climbs
    end
  
    def update
        if review_params.present? && review_params[:climb_id].present?
          @review.update(review_params)
             review_save
        else
         flash[:message] = "Your spray is missing some necessary content! Please try again."
         climbs_for_render_edit
       end
    end

    def destroy        
        if @review
          @review.destroy
          flash[:message] = "The spray has been removed!"
          redirect_to reviews_path
        else
          flash[:danger] = "The spray could not be removed!"
          redirect_to review_path(@review)
        end
    end

    private

    def review_params
        params.require(:review).permit(:stars, :title, :content, :climb_id)
    end

    def find_review
        @review = Review.find_by(id: params[:id])
    end

    def find_climb
        @climb = Climb.find_by_id(params[:climb_id])
    end

    def created_by_current_user
        unless @review.user_id == current_user.id
          flash[:danger] = "You cannot change or remove this spray because you did not create it!"
          redirect_to review_path(@review)
        end
    end

    def climbs
        @climbs = Climb.all.alphabetical_order
    end 

    def climbs_for_render_edit
        climbs
        render :edit
    end 
    
    def review_save
        if @review.save
            flash[:message] = "'#{@review.title}' has been updated!"
            redirect_to review_path(@review)
        else
            climbs_for_render_edit
        end
    end 

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

    def github
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
         sign_in_and_redirect @user  
        set_flash_message(:notice, :success, kind: "github") if is_navigational_format?
      else
        session["devise.github_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/climbs_helper.rb
module ClimbsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/application/home.html.erb
<h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Hey, <%= current_user.username %>! Time to crush!</h1>

<h2>What do you want to do today?</h2>

   <body>
<h3> Spray: </h3>
    <ul>
    <li><%= link_to "Add a new climb", new_climb_path %></li>
    <li> <%= link_to "Add a new review", new_review_path %> </li>
    <li> </br> </li>
    </ br>
<h3> Send: </h3>
    <li> <%= link_to "See all climbs", climbs_path %> </li>
    <li> <%= link_to "See all reviews", reviews_path %> </li>
    <li> <%= link_to "See Star-Chasers", climbs_grouped_ratings_path %> </li>
    <li> </br> </li>
    </ br>
<h3> Still deciding? </h3>
    <li> <%= link_to "Search for a climb to send or spray", climbs_path %> </li>
    <ul>
</body>
    

app/views/application/welcome.html.erb
<h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Spray to Send<h1>
<h2>Hello climber!</h2>
<p>
You must be ready to send. Or spray. Or both. </br></br>
Either way, you've come to the right place. </br></br>

<i>Spray to Send</i> is the climber's catch-all for all things send-related. Here, climbers can add spray for recents sends, pick out new projects, scope out climbs based on star quality, and keep coming back for more. Spoiler alert--beta spray abounds in these parts. Come chalked up and ready to go!</br>
</br>
So, sign up and have a look around! Your next send or spray is just a few clicks (and a heel hook or two) away! 
</p>
<h3><i>Let's do this.</i></h3>

app/views/climbs/_form.html.erb
<%= render partial: 'layouts/errors', locals:{object: @climb}%>
<%= form_for(@climb) do |f| %>
<div>
    <%= f.label :name %>
    <%= f.text_field :name%>
</div>

<div>
    <%= f.label :grade %>
    <%= f.text_field :grade %>
</div>

<div>
    <%= f.label :description %>
    <%= f.text_field :description %>
    </ br>
</div> 

<p>Please select a location: <%= f.collection_select :location_id, @locations, :id, :name, include_blank: "Pick one" %></p>

<p>Or create a new location:
<%= f.fields_for :location do |l| %></br>
    <%= l.text_field :name %>
<% end %></p>
<br />
<%= f.submit %>

<% end %>

app/views/climbs/index.html.erb
<h2>Ready to Send?</h2></br>

    <%= form_tag("/search", method: "get") do %>
   <b><i> <%= label_tag :query, "Search for a climb:" %> </i></b>
    <%= text_field_tag :query, "", class:"form-control" %>
    <%= submit_tag "Search", class: "btn btn-sm btn-secondary" %>
    <% end %>
<ul>
<% @climbs.each do |c| %>
   <li> </br> <h3> &nbsp; &nbsp; &nbsp; &nbsp; <%= link_to c.name, climb_path(c) %> - <%= c.grade.capitalize %> - <%=c.description%></h3></li>
<% end %>
</ul>
     

app/views/climbs/new.html.erb
<h2>What are you climbing today?</h2>
<%= render partial: 'form'%>

app/views/climbs/ratings.html.erb
<h1>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; The Star-Chasers</h1>
<h2></h2>
</br>
<% @climbs.each do |c| %>
    <h2><%= link_to c.name, climb_path(c)  %> - <%= c.grade.capitalize %> </h2>
    <ul>
    <% c.reviews.each do |r| %>
        <h4><li> &nbsp; &nbsp; &nbsp; &nbsp; <i><%= link_to r.title, review_path(r) %> - <%= pluralize(r.stars, "star") %></i></li></h4>
    <% end %>
    </br>
   </ul>
<% end %>
</br>

app/views/climbs/show.html.erb
<h1>The Climb:</h1>

<h2><i><%= @climb.name %></i></h2>

<h3>Grade: <%= @climb.grade.capitalize %></h3></br>

<p><b>Description:</b> <%= @climb.description%> </p></br>


<% if @climb.reviews.present? %>
    <%= link_to "The Spray-down", climb_reviews_path(@climb) %> </br>
    <%= link_to "Add Spray", new_climb_review_path(@climb)%>
<% else %>
    <%= link_to "Add Spray", new_climb_review_path(@climb)%>
<% end %>

app/views/layouts/_alerts.html.erb
<% flash.keys.each do |k| %>
    <% if k == "danger" %>
      <div class="alert alert-danger" role="alert">
    <% else %>
      <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <% end %>
       <i> <%= flash[k] %></i>
      </div>
  <% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h3>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><i><%= msg %></i></li>
    <% end %>
    </br>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
  
   <% if !user_signed_in? %> &nbsp; &nbsp; 
     <%= link_to "Welcome", root_path %> &nbsp; &nbsp; &nbsp; &nbsp; 
     <%= link_to "Log in", new_user_session_path %> &nbsp; &nbsp; &nbsp; &nbsp; 
     <%= link_to "Sign Up", new_user_registration_path %> &nbsp; &nbsp; &nbsp; &nbsp;
     <%= link_to "Sign Up with Github", user_github_omniauth_authorize_path %>
   <% else %>
    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <%= link_to "Home", root_path %> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <%= link_to "Logout", destroy_user_session_path, method: "delete" %>
   <% end %>






 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>SprayToSend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <div class="wrapper">

      <%= render 'layouts/alerts' %>    
      <%= yield %>

    <footer class="branding">
      <small>&copy; 2020 <strong>Spray-to-Send</strong></small> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <%= render 'layouts/nav' %>
    </footer>

  </div>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <!--[if lt IE 7]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
    <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
  <![endif]-->
      

  </body>
</html>

app/views/reviews/_form.html.erb
<%= render partial: 'layouts/errors', locals:{object: @review}%>

<%= form_for(@review) do |f| %>
<% if params[:climb_id] %>
    <%= f.hidden_field :climb_id %>
<% else %>
    <div></br>
        <%= f.label :climb_id, "Select a climb!" %>
        <%= f.collection_select :climb_id, @climbs, :id, :name, include_blank: true %>
    </div></br> 
    <% end %>
<div>
    <%= f.label :stars %>
    <%= f.number_field :stars, min:1, max:5 %>
</div></br>

<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
</div></br>

<div>
    <%= f.label :content %> &nbsp;
    <%= f.text_area :content %>
</div></br>
</br>
<%= f.submit %>

<% end %>

app/views/reviews/edit.html.erb
<h2> Edit Spray for <i><%=@review.climb.name%></i>:</h2>

<%= render partial: 'form'%>

app/views/reviews/index.html.erb
<% if @climb %>
    <h1> Full Spray-down for <i><%= @climb.name %></i>!</h1>
        <h2> Location: <%= @climb.location.name %></h2>
        <% if @reviews.present? %>
            <ul>
            <h3> Reviews: </h3> </br>
            <% @reviews.each do |r| %>
            <li> <h4> - <%= r.title %> - <%= pluralize(r.stars, "star") %> </h4> </li>
            <p> <i><%= r.content %></i> </p>
        <% end %>
            <ul> </br>
            <%= link_to "Add Spray", new_climb_review_path(@climb)%>
        <% else %>
        <p> Be the change. Add the first review. </p>
        <%= link_to "Add Spray", new_climb_review_path(@climb) %>
        <% end %>
 
<% else %>
    <h1> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  All the Spray! </h1>
       <h2></h2>
       <h2> Reviews: </h2></br>   
            <% @climbs.each do |c| %>  
                <%  if c.reviews.present? %>
                <ul>
                  <% c.reviews.each do |r| %>
                     <li> <h4> <%= link_to r.climb.name, review_path(r) %> - <%= r.title %> - <%= pluralize(r.stars, "star") %> </h4> </li>
                     <p> <i><%= r.content %></i> </p>
                     </br>
                  <% end %>
                </ul>
            <% end %>
    <% end %>
<% end %>

app/views/reviews/new.html.erb
<% if @climb %>
    <h2> Add Spray to <i><%=@climb.name%></i>!</h2>
<% else %>
    <h2> Add Spray! </h2>
<% end %>

<%= render partial: 'form'%>

 

app/views/reviews/show.html.erb
<h1>The Spray:</h1>

<h2><i><%= @review.climb.name %> </i></h2>

<h3><%= @review.title %></h3> 

<h3><% if @review.stars.present? %>
<%= pluralize(@review.stars, "star") %>
<% end %></h3>   

<p></br><i><%= @review.content %></i></p></br>


<%= link_to "The Climb", climb_path(@review.climb) %> </br>
<%= link_to "The Spray-down", climb_reviews_path(@review.climb) %> </br>
<%= link_to "Add Spray", new_climb_review_path(@review.climb)%> </br>
<%= link_to "Edit Spray", edit_review_path(@review)%>

<%= form_for @review, method: :delete do |f| %> </br>
    <%= f.submit "Delete", class:"btn btn-sm btn-danger btn-block" %>
<% end %>